//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rehberKayitUygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblKayitlar
    {
        public int Id { get; set; }
        
        [Display(Name ="Telefon Numarası")]
        [Required(ErrorMessage = "Numara girmediniz!")]
        public string tel { get; set; }

        [Display(Name = "Adı")]
        [Required(ErrorMessage ="Ad girmediniz!")]
        public string ad { get; set; }


        
        [Display(Name = "Soyadı")]
        public string soyAd { get; set; }
    }
}
